### Introduction
Recurrent neural networks (RNN) are a class of neural networks that is powerful for modeling sequence data such as `time series` or `natural language`.


### Keras RNN API
1. **Ease of use** Built-in Keras RNN API LAyers
    * keras.layers.RNN
    * keras.layers.LSTM(Long Shot Tream Memory)
    * keras.layers.GRU(Gated recurrent unit)

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
model =keras.Sequential()
model.add(layers.Embedding(input_dim=1000,output_dim=64))

In [4]:
model.add(layers.LSTM(128)) # interal Unit

In [5]:
model.add(layers.Dense(10))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          64000     
_________________________________________________________________
lstm (LSTM)                  (None, 128)               98816     
_________________________________________________________________
dense (Dense)                (None, 10)                1290      
Total params: 164,106
Trainable params: 164,106
Non-trainable params: 0
_________________________________________________________________


In [7]:
model = keras.Sequential()
model.add(layers.Embedding(input_dim=1000, output_dim=64))

# The output of GRU will be a 3D tensor of shape (batch_size, timesteps, 256)
model.add(layers.GRU(256, return_sequences=True))

# The output of SimpleRNN will be a 2D tensor of shape (batch_size, 128)
model.add(layers.SimpleRNN(128))

model.add(layers.Dense(10))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 64)          64000     
_________________________________________________________________
gru (GRU)                    (None, None, 256)         247296    
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 128)               49280     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 361,866
Trainable params: 361,866
Non-trainable params: 0
_________________________________________________________________


In [8]:
encodeer_vocab = 1000
decoder_vocab = 2000

encoder_input =layers.Input(shape=(None,))
encoder_embedded = layers.Embedding(input_dim=encodeer_vocab, output_dim=64)(encoder_input)

# Addition to ouput layer
output,state_h,state_c = layers.LSTM(64,return_state=True,name="encoder")(encoder_embedded)
encoder_state = [state_h,state_c]


In [9]:
decoder_input = layers.Input(shape=(None,))
decoder_embedded = layers.Embedding(input_dim=encodeer_vocab, output_dim=64)(decoder_input)


In [10]:
decoder_output  =layers.LSTM(64,name="decoder")(decoder_embedded,initial_state=encoder_state)
output = layers.Dense(10)(decoder_output)

In [11]:
model = keras.Model([encoder_input,decoder_input],output)
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, None)]       0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, None)]       0                                            
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, None, 64)     64000       input_1[0][0]                    
__________________________________________________________________________________________________
embedding_3 (Embedding)         (None, None, 64)     64000       input_2[0][0]                    
______________________________________________________________________________________________

In [12]:
## RNN layers and RNN cells

In [16]:
paragraph1 = np.random.random((20,10,50)).astype(np.float32)
paragraph2 = np.random.random((20,10,50)).astype(np.float32)
paragraph3 = np.random.random((20,10,50)).astype(np.float32)

In [17]:
lstm_layes = layers.LSTM(64,stateful=True)

In [18]:
output1 = lstm_layes(paragraph1)
output1

<tf.Tensor: shape=(20, 64), dtype=float32, numpy=
array([[ 0.149182  ,  0.0984559 , -0.03400996, ...,  0.3324095 ,
        -0.04334225,  0.26871008],
       [ 0.01541198,  0.02514893,  0.02832633, ...,  0.23924802,
         0.02662718,  0.2031984 ],
       [ 0.20027432,  0.06544052, -0.06190866, ...,  0.31671703,
        -0.05458254,  0.3291244 ],
       ...,
       [ 0.12431772,  0.09712484,  0.04886755, ...,  0.2619186 ,
         0.03659557,  0.1797513 ],
       [ 0.00150693,  0.05600857,  0.07027224, ...,  0.20397915,
        -0.0177468 ,  0.190222  ],
       [ 0.07801418,  0.08912748,  0.0187683 , ...,  0.33133367,
         0.07407717,  0.21878695]], dtype=float32)>

In [19]:
output1 = lstm_layes(paragraph2)
output1 = lstm_layes(paragraph3)

In [21]:
output1

<tf.Tensor: shape=(20, 64), dtype=float32, numpy=
array([[ 0.0231192 ,  0.06115599, -0.05701875, ...,  0.23524678,
         0.01739244,  0.22129564],
       [ 0.13437752,  0.08276025,  0.0495629 , ...,  0.17493336,
         0.04121735,  0.22465427],
       [ 0.02950412,  0.06756306, -0.01892514, ...,  0.32155162,
        -0.00428251,  0.29230082],
       ...,
       [ 0.03360521, -0.04926559, -0.03957021, ...,  0.36741382,
        -0.01722551,  0.27341232],
       [ 0.05464854,  0.03126886, -0.07255708, ...,  0.29710826,
         0.00880164,  0.23049855],
       [ 0.11449699,  0.0700281 ,  0.09563901, ...,  0.3397338 ,
         0.04523849,  0.19895108]], dtype=float32)>

In [23]:
lstm_layes.reset_states()

In [25]:
paragraph1 = np.random.random((20,10,50)).astype(np.float32)
paragraph2 = np.random.random((20,10,50)).astype(np.float32)
paragraph3 = np.random.random((20,10,50)).astype(np.float32)

lstm_layer = layers.LSTM(64, stateful=True)
output = lstm_layer(paragraph1)
output = lstm_layer(paragraph2)

existing_state = lstm_layer.states

In [26]:
new_lstm_layer = layers.LSTM(64)
new_output = new_lstm_layer(paragraph3, initial_state=existing_state)

In [27]:
new_output

<tf.Tensor: shape=(20, 64), dtype=float32, numpy=
array([[-0.13040799, -0.14051014,  0.1440264 , ..., -0.21907756,
        -0.2212108 ,  0.34351596],
       [-0.14163095, -0.2013616 ,  0.05614021, ..., -0.13782127,
        -0.10555   ,  0.27189273],
       [-0.09240718, -0.18324399,  0.17198919, ..., -0.11951485,
        -0.18945704,  0.28465444],
       ...,
       [-0.1302602 , -0.24054158,  0.1387838 , ..., -0.19101603,
        -0.14297906,  0.38465154],
       [-0.10163777, -0.14202139,  0.04231317, ..., -0.11261632,
        -0.13500588,  0.2887042 ],
       [-0.06895519, -0.17153624,  0.03698158, ..., -0.19048609,
        -0.2133256 ,  0.3297368 ]], dtype=float32)>