# Welcome to Deep Learning! #

Welcome to **Introduction to Deep Learning** course! You're about to learn all you need to get started building your own deep neural networks. Using Keras(NN Modeling) and Tensorflow(Numpy) you'll learn how to:
- Create a **fully-connected** neural network architecture
- Apply neural nets to two classic ML problems: **regression** and **classification**
- Train neural nets with **stochastic gradient descent**, and
- Improve performance with **dropout**, **batch normalization**, and other techniques

The tutorials will introduce you to these topics with fully-worked examples, and then in the exercises, you'll explore these topics in more depth and apply them to real-world datasets.

Let's get started!

# What is Deep Learning? #

Some of the most impressive advances in artificial intelligence in recent years have been in the field of **deep learning**. `Natural language translation, image recognition, and game playing` are all tasks where deep learning models have neared or even exceeded human-level performance.

So what is deep learning? **Deep learning** is an approach to machine learning characterized by deep stacks of computations. This depth of computation is what has enabled deep learning models to disentangle the kinds of complex and hierarchical patterns found in the most challenging real-world datasets.

Through their power and scalability **neural networks** have become the defining model of deep learning.  Neural networks are composed of neurons, where each neuron individually performs only a simple computation. The power of a neural network comes instead from the complexity of the connections these neurons can form.

# The Linear Unit #

So let's begin with the fundamental component of a neural network: the individual neuron. As a diagram, a **neuron** (or **unit**) with one input looks like:

<figure style="padding: 1em;">
<img src="https://i.imgur.com/mfOlDR6.png" width="250" alt="Diagram of a linear unit."/>
    <figcaption style="textalign: center; font-style: italic"><center>The Linear Unit: $y = w x + b$
</center></figcaption>
</figure>

The input is `x`. Its connection to the neuron has a **weight** which is `w`. Whenever a value flows through a connection, you multiply the value by the connection's weight. For the input `x`, what reaches the neuron is `w * x`. A neural network "learns" by modifying its weights.

The `b` is a special kind of weight we call the **bias**. The bias doesn't have any input data associated with it; instead, we put a `1` in the diagram so that the value that reaches the neuron is just `b` (since `1 * b = b`). The bias enables the neuron to modify the output independently of its inputs.

The `y` is the value the neuron ultimately outputs. To get the output, the neuron sums up all the values it receives through its connections. This neuron's activation is `y = w * x + b`, or as a formula $y = w x + b$.

<blockquote style="margin-right:auto; margin-left:auto; background-color: #ebf9ff; padding: 1em; margin:24px;">
    <strong>Does the formula $y=w x + b$ look familiar?</strong><br>
It's an equation of a line! It's the slope-intercept equation, where $w$ is the slope and $b$ is the y-intercept. 
</blockquote>

## Providing the Data

Next up we'll feed in some data. In this case we are taking 6 xs and 6ys. You can see that the relationship between these is that y=2x-1, so where x = -1, y=-3 etc. etc. 

* `2`: Slope or Weight
* `-1`: bias or Intreception 


A python library called 'Numpy' provides lots of array type data structures that are a defacto standard way of doing it. We declare that we want to use these by specifying the values as an np.array[]


In [45]:
import numpy as np

In [46]:
xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

|X|Y|
|--|--|
|4.0|7.0|
|5.0|9.0|
|6.0|11.0|
|7.0|13.0|
|8.0|15.0|
|9.0|17.0|
|10.0|?|

In [47]:
xs.shape

(6,)

In [48]:
xs.ndim

1

* if X is Varing 1 time then Y will Varing from 2

In [49]:
#y = mx+b
slope = 2
bias = -1

In [50]:
y = slope*xs+bias
y

array([-3., -1.,  1.,  3.,  5.,  7.])

In [51]:
new_x_values = 10.0
y = slope*new_x_values+bias
y

19.0

In [52]:
slope1 = 0.99
y = slope1*xs+bias
y

array([-1.99, -1.  , -0.01,  0.98,  1.97,  2.96])

In [53]:
import tensorflow  as tf
from tensorflow import keras

In [54]:
model = tf.keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])

In [55]:
model

In [56]:
model.compile(optimizer='sgd',loss='mean_squared_error')

In [67]:
model.fit(xs,ys,epochs=125)

Epoch 1/125
1/1 [==============================] - 0s 994us/step - loss: 0.0194
Epoch 2/125
1/1 [==============================] - 0s 0s/step - loss: 0.0190
Epoch 3/125
1/1 [==============================] - 0s 998us/step - loss: 0.0186
Epoch 4/125
1/1 [==============================] - 0s 986us/step - loss: 0.0183
Epoch 5/125
1/1 [==============================] - 0s 0s/step - loss: 0.0179
Epoch 6/125
1/1 [==============================] - 0s 998us/step - loss: 0.0175
Epoch 7/125
1/1 [==============================] - 0s 0s/step - loss: 0.0171
Epoch 8/125
1/1 [==============================] - 0s 997us/step - loss: 0.0168
Epoch 9/125
1/1 [==============================] - 0s 998us/step - loss: 0.0165
Epoch 10/125
1/1 [==============================] - 0s 0s/step - loss: 0.0161
Epoch 11/125
1/1 [==============================] - 0s 0s/step - loss: 0.0158
Epoch 12/125
1/1 [==============================] - 0s 997us/step - loss: 0.0155
Epoch 13/125
1/1 [==============================] - 

In [68]:
model.predict([10.0])

array([[18.88771]], dtype=float32)

# Example - The Linear Unit as a Model #

Though individual neurons will usually only function as part of a larger network, it's often useful to start with a single neuron model as a baseline. Single neuron models are *linear* models. 

Let's think about how this might work on a dataset like [80 Cereals](https://www.kaggle.com/crawford/80-cereals). Training a model with `'sugars'` (grams of sugars per serving) as input and `'calories'` (calories per serving) as output, we might find the bias is `b=90` and the weight is `w=2.5`. We could estimate the calorie content of a cereal with 5 grams of sugar per serving like this:

<figure style="padding: 1em;">
<img src="https://i.imgur.com/yjsfFvY.png" width="1000" alt="Computing with the linear unit.">
<figcaption style="textalign: center; font-style: italic"><center>Computing with the linear unit.
</center></figcaption>
</figure>

And, checking against our formula, we have $calories = 2.5 \times 5 + 90 = 102.5$, just like we expect.

# Multiple Inputs #

The *80 Cereals* dataset has many more features than just `'sugars'`. What if we wanted to expand our model to include things like fiber or protein content? That's easy enough. We can just add more input connections to the neuron, one for each additional feature. To find the output, we would multiply each input to its connection weight and then add them all together.

<figure style="padding: 1em;">
<img src="https://i.imgur.com/vyXSnlZ.png" width="300" alt="Three input connections: x0, x1, and x2, along with the bias.">
<figcaption style="textalign: center; font-style: italic"><center>A linear unit with three inputs.
</center></figcaption>
</figure>

The formula for this neuron would be $y = w_0 x_0 + w_1 x_1 + w_2 x_2 + b$. A linear unit with two inputs will fit a plane, and a unit with more inputs than that will fit a hyperplane.

# Linear Units in Keras #

The easiest way to create a model in Keras is through `keras.Sequential`, which creates a neural network as a stack of *layers*. We can create models like those above using a *dense* layer (which we'll learn more about in the next lesson).

We could define a linear model accepting three input features (`'sugars'`, `'fiber'`, and `'protein'`) and producing a single output (`'calories'`) like so:

In [69]:
from tensorflow import keras
from tensorflow.keras import layers

# Create a network with 1 linear unit
model = keras.Sequential([
    layers.Dense(units=1, input_shape=[3])
])

With the first argument, `units`, we define how many outputs we want. In this case we are just predicting `'calories'`, so we'll use `units=1`. 

With the second argument, `input_shape`, we tell Keras the dimensions of the inputs. Setting `input_shape=[3]` ensures the model will accept three features as input (`'sugars'`, `'fiber'`, and `'protein'`).

This model is now ready to be fit to training data!

<blockquote style="margin-right:auto; margin-left:auto; background-color: #ebf9ff; padding: 1em; margin:24px;">
    <strong>Why is <code>input_shape</code> a Python list?</strong><br>
The data we'll use in this course will be tabular data, like in a Pandas dataframe. We'll have one input for each feature in the dataset. The features are arranged by column, so we'll always have <code>input_shape=[num_columns]</code>.

The reason Keras uses a list here is to permit use of more complex datasets. Image data, for instance, might need three dimensions: <code>[height, width, channels]</code>.
</blockquote>

# Your Turn #

[**Define a linear model**](https://www.kaggle.com/kernels/fork/11887334) for the *Red Wine Quality* dataset.

---




*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum/191966) to chat with other Learners.*