In [11]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf

In [2]:
[
  ["Hello", "world", "!"],
  ["How", "are", "you", "doing", "today"],
  ["The", "weather", "will", "be", "nice", "tomorrow"],
]

[['Hello', 'world', '!'],
 ['How', 'are', 'you', 'doing', 'today'],
 ['The', 'weather', 'will', 'be', 'nice', 'tomorrow']]

In [4]:
# After vocabulary lookup, the data might be vectorized as integers, e.g.:
raw_input = [[71, 1331, 4231],
[73, 8, 3215, 55, 927],
[83, 91, 1, 645, 1253, 927]]

In [5]:
padding_input = keras.preprocessing.sequence.pad_sequences(raw_input,padding='post')  

In [6]:
print(padding_input)

[[  71 1331 4231    0    0    0]
 [  73    8 3215   55  927    0]
 [  83   91    1  645 1253  927]]


In [7]:
padding_input = keras.preprocessing.sequence.pad_sequences(raw_input,padding='pre')  

In [8]:
print(padding_input)

[[   0    0    0   71 1331 4231]
 [   0   73    8 3215   55  927]
 [  83   91    1  645 1253  927]]


In [12]:
t = tf.constant([[1, 2, 3], 
                [4, 5, 6]])
paddings = tf.constant([[1, 1,], 
                        [2, 2]])

In [13]:
tf.pad(t,paddings,"CONSTANT") # We are adding Zero

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [14]:
tf.pad(t,paddings,'REFLECT') # we will add  Ne pix values

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[6, 5, 4, 5, 6, 5, 4],
       [3, 2, 1, 2, 3, 2, 1],
       [6, 5, 4, 5, 6, 5, 4],
       [3, 2, 1, 2, 3, 2, 1]], dtype=int32)>

In [15]:
tf.pad(t, paddings, "SYMMETRIC")

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[2, 1, 1, 2, 3, 3, 2],
       [2, 1, 1, 2, 3, 3, 2],
       [5, 4, 4, 5, 6, 6, 5],
       [5, 4, 4, 5, 6, 6, 5]], dtype=int32)>

**VALID:** it means no padding and it assumes that all the dimensions are valid so that the input image gets fully covered by a filter and the stride specified by you.

**SAME:** it applies padding to the input image so that the input image gets fully covered by the filter and specified stride
* It is called SAME because, for stride 1 , the output will be the same as the input.

![](https://lh3.googleusercontent.com/-aQpVb4KyrTQ/X_KmwlRn5yI/AAAAAAAAsMc/-hK90My8yP01Ko2zFxLVGtoHRD-xBWeZgCK8BGAsYHg/s0/2021-01-03.png)